name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Set default permissions to read-only for security
permissions:
  contents: read

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
      fail-fast: false
    name: Node.js ${{ matrix.node-version }}
    env:
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Run smoke test
        run: |
          # Start the server in background
          pnpm start &
          SERVER_PID=$!

          # Wait for server to be ready
          echo "Waiting for server to start..."
          timeout 30 bash -c 'until curl -f http://localhost:3000 > /dev/null 2>&1; do sleep 1; done'

          # Check if server is responding
          curl -f http://localhost:3000 || exit 1

          # Cleanup
          kill $SERVER_PID
